/********************************************************************
* KDetSimDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error KDetSimDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevKDetSimDict();
extern G__DLLEXPORT void G__set_cpp_environmentKDetSimDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableKDetSimDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceKDetSimDict();
extern G__DLLEXPORT void G__cpp_setup_typetableKDetSimDict();
extern G__DLLEXPORT void G__cpp_setup_memvarKDetSimDict();
extern G__DLLEXPORT void G__cpp_setup_globalKDetSimDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncKDetSimDict();
extern G__DLLEXPORT void G__cpp_setup_funcKDetSimDict();
extern G__DLLEXPORT void G__cpp_setupKDetSimDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__KDetSimDictLN_TClass;
extern G__linked_taginfo G__KDetSimDictLN_TBuffer;
extern G__linked_taginfo G__KDetSimDictLN_TMemberInspector;
extern G__linked_taginfo G__KDetSimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__KDetSimDictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__KDetSimDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__KDetSimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KDetSimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__KDetSimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__KDetSimDictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__KDetSimDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__KDetSimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KDetSimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__KDetSimDictLN_TArrayF;
extern G__linked_taginfo G__KDetSimDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__KDetSimDictLN_TF1;
extern G__linked_taginfo G__KDetSimDictLN_TH1D;
extern G__linked_taginfo G__KDetSimDictLN_TH1F;
extern G__linked_taginfo G__KDetSimDictLN_TRandom;
extern G__linked_taginfo G__KDetSimDictLN_TGraph;
extern G__linked_taginfo G__KDetSimDictLN_TH3I;
extern G__linked_taginfo G__KDetSimDictLN_TH3F;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__KDetSimDictLN_TH2F;
extern G__linked_taginfo G__KDetSimDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__KDetSimDictLN_TVector3;
extern G__linked_taginfo G__KDetSimDictLN_KField;
extern G__linked_taginfo G__KDetSimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__KDetSimDictLN_TFile;
extern G__linked_taginfo G__KDetSimDictLN_TROOT;
extern G__linked_taginfo G__KDetSimDictLN_KMaterial;
extern G__linked_taginfo G__KDetSimDictLN_KStruct;
extern G__linked_taginfo G__KDetSimDictLN_TF3;
extern G__linked_taginfo G__KDetSimDictLN_KGeometry;
extern G__linked_taginfo G__KDetSimDictLN_KDetector;
extern G__linked_taginfo G__KDetSimDictLN_KPad;
extern G__linked_taginfo G__KDetSimDictLN_K3D;
extern G__linked_taginfo G__KDetSimDictLN_KPixel;
extern G__linked_taginfo G__KDetSimDictLN_KStrip;
extern G__linked_taginfo G__KDetSimDictLN_KMesh;
extern G__linked_taginfo G__KDetSimDictLN_KImplant3D;
extern G__linked_taginfo G__KDetSimDictLN_KImplant2D;

/* STUB derived class for protected member access */
